#!/bin/bash

echo "🎯 CREDENCIALES QUE FUNCIONAN AHORA"
echo "==================================="
echo ""
echo "✅ USUARIO: admin"
echo "✅ CONTRASEÑA: password123"
echo ""
echo "🌐 SITIOS DONDE USARLAS:"
echo "------------------------"
echo "📸 Galería: https://thebadgerspage.onrender.com/galeria"
echo "🏆 Torneo:  https://thebadgerspage.onrender.com/torneo"
echo ""
echo "🔍 CÓMO HACER LOGIN:"
echo "-------------------"
echo "1. Ve a cualquiera de los sitios de arriba"
echo "2. Haz click en 'Iniciar Sesión para Subir Fotos' (galería)"
echo "3. O haz click en 'Iniciar Sesión' (torneo)"
echo "4. Usa: admin / password123"
echo ""
echo "✅ DEBERÍAS PODER:"
echo "-----------------"
echo "• Ver todas las fotos (sin login)"
echo "• Subir fotos nuevas (con login admin)"
echo "• Acceder al sistema de torneo completo"
echo ""
echo "⚠️  SOBRE LAS IMÁGENES ROTAS:"
echo "----------------------------"
echo "• Las imágenes que ves rotas se perdieron en deployments anteriores"
echo "• Las nuevas que subas funcionarán (temporalmente)"
echo "• Para solución permanente necesitamos configurar Cloudinary"
echo ""
echo "🚀 PRUEBA AHORA: https://thebadgerspage.onrender.com/galeria"
