# Generated by Django 5.2.4 on 2025-07-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='galeria/')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(blank=True, choices=[('img', 'Imagen'), ('video', 'Video')], max_length=10)),
            ],
        ),
    ]
