# Generated by Django 5.2.4 on 2025-08-10 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galeriaitem_usuario_alter_galeriaitem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('peso_minimo', models.FloatField(help_text='Peso mínimo en kg')),
                ('peso_maximo', models.FloatField(help_text='Peso máximo en kg')),
                ('cinturon', models.CharField(choices=[('blanca', 'Blanca'), ('azul', 'Azul'), ('purpura', 'Púrpura'), ('marron', 'Marrón'), ('negra', 'Negra')], max_length=20)),
                ('grupo_edad', models.CharField(choices=[('juvenil', 'Juvenil (16-17)'), ('adulto', 'Adulto (18-29)'), ('master1', 'Master 1 (30-35)'), ('master2', 'Master 2 (36-40)'), ('master3', 'Master 3 (41-45)'), ('master4', 'Master 4 (46-50)'), ('master5', 'Master 5 (51+)')], max_length=30)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada')], default='abierta', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estructura', models.JSONField(help_text='Estructura de la llave en formato JSON')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('bloqueada', models.BooleanField(default=False, help_text='Si está bloqueada no se puede editar')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llave', to='core.categoria')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('academia', models.CharField(default='The Badgers', max_length=200)),
                ('peso', models.FloatField(help_text='Peso en kg')),
                ('cinturon', models.CharField(choices=[('blanca', 'Blanca'), ('azul', 'Azul'), ('purpura', 'Púrpura'), ('marron', 'Marrón'), ('negra', 'Negra')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.categoria')),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Lucha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.CharField(help_text='Ej: Final, Semifinal, Cuartos', max_length=50)),
                ('duracion_segundos', models.IntegerField(default=300, help_text='Duración en segundos')),
                ('tiempo_transcurrido', models.IntegerField(default=0, help_text='Tiempo transcurrido en segundos')),
                ('puntos_p1', models.IntegerField(default=0)),
                ('ventajas_p1', models.IntegerField(default=0)),
                ('penalizaciones_p1', models.IntegerField(default=0)),
                ('puntos_p2', models.IntegerField(default=0)),
                ('ventajas_p2', models.IntegerField(default=0)),
                ('penalizaciones_p2', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('resultado', models.CharField(blank=True, help_text='Ej: Por puntos, Sumisión, etc.', max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luchas', to='core.categoria')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luchas_ganadas', to='core.participante')),
                ('participante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luchas_como_p1', to='core.participante')),
                ('participante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luchas_como_p2', to='core.participante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('planificacion', 'Planificación'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.torneo'),
        ),
    ]
