# Generated by Django 4.2.10 on 2025-10-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_galeriaitem_options_galeriaitem_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaitem',
            name='url',
            field=models.URLField(blank=True, help_text='URL externa (ej. Cloudinary)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galeriaitem',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
