# Generated by Django 5.2.4 on 2025-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_llave_participante_lucha_torneo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cinturon',
            field=models.CharField(blank=True, choices=[('blanca', 'Blanca'), ('azul', 'Azul'), ('purpura', 'Púrpura'), ('marron', 'Marrón'), ('negra', 'Negra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='grupo_edad',
            field=models.CharField(blank=True, choices=[('juvenil', 'Juvenil (16-17)'), ('adulto', 'Adulto (18-29)'), ('master1', 'Master 1 (30-35)'), ('master2', 'Master 2 (36-40)'), ('master3', 'Master 3 (41-45)'), ('master4', 'Master 4 (46-50)'), ('master5', 'Master 5 (51+)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='peso_maximo',
            field=models.FloatField(blank=True, help_text='Peso máximo en kg', null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='peso_minimo',
            field=models.FloatField(blank=True, help_text='Peso mínimo en kg', null=True),
        ),
    ]
