# Generated by Django 5.2.4 on 2025-08-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_cinturon_alter_categoria_genero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['tipo_categoria', 'peso_minimo']},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='cinturon',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='grupo_edad',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='genero',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(choices=[('principiante_gi', 'Principiante GI'), ('intermedio_gi', 'Intermedio GI'), ('avanzado_gi', 'Avanzado GI'), ('principiante_nogi', 'Principiante No GI'), ('intermedio_nogi', 'Intermedio No GI'), ('avanzado_nogi', 'Avanzado No GI'), ('blanca', 'Blanca'), ('azul', 'Azul'), ('violeta', 'Violeta'), ('marron', 'Marrón'), ('negro', 'Negro')], default='blanca', max_length=30),
        ),
        migrations.AddField(
            model_name='participante',
            name='categoria_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_asignados', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='participante',
            name='torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.torneo'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cinturon',
            field=models.CharField(choices=[('blanca', 'Blanca'), ('azul', 'Azul'), ('violeta', 'Violeta'), ('marron', 'Marrón'), ('negro', 'Negro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso en kg', null=True),
        ),
    ]
