# Generated by Django 5.2.4 on 2025-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categoria_options_alter_participante_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lucha',
            name='resultado',
        ),
        migrations.AddField(
            model_name='llave',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llave',
            name='tipo_eliminacion',
            field=models.CharField(choices=[('simple', 'Eliminación Simple'), ('doble', 'Eliminación Doble')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='lucha',
            name='cronometro_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lucha',
            name='derribos_p1',
            field=models.IntegerField(default=0, help_text='Derribos (2 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='derribos_p2',
            field=models.IntegerField(default=0, help_text='Derribos (2 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='guardas_pasadas_p1',
            field=models.IntegerField(default=0, help_text='Guardas pasadas (3 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='guardas_pasadas_p2',
            field=models.IntegerField(default=0, help_text='Guardas pasadas (3 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='montadas_p1',
            field=models.IntegerField(default=0, help_text='Montadas (4 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='montadas_p2',
            field=models.IntegerField(default=0, help_text='Montadas (4 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='posicion_llave',
            field=models.IntegerField(blank=True, help_text='Posición en la llave', null=True),
        ),
        migrations.AddField(
            model_name='lucha',
            name='resultado_detalle',
            field=models.CharField(blank=True, help_text='Ej: Armbar, Guillotine, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='lucha',
            name='rodillazos_p1',
            field=models.IntegerField(default=0, help_text='Rodillazos (2 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='rodillazos_p2',
            field=models.IntegerField(default=0, help_text='Rodillazos (2 puntos c/u)'),
        ),
        migrations.AddField(
            model_name='lucha',
            name='tipo_victoria',
            field=models.CharField(blank=True, choices=[('puntos', 'Por Puntos'), ('sumision', 'Por Sumisión'), ('ventajas', 'Por Ventajas'), ('penalizacion', 'Por Penalización'), ('descalificacion', 'Descalificación'), ('wo', 'Walk Over')], max_length=20),
        ),
        migrations.AlterField(
            model_name='llave',
            name='estructura',
            field=models.JSONField(default=dict, help_text='Estructura de la llave en formato JSON'),
        ),
        migrations.AlterField(
            model_name='lucha',
            name='duracion_segundos',
            field=models.IntegerField(default=300, help_text='Duración en segundos (5 min default)'),
        ),
        migrations.AlterField(
            model_name='lucha',
            name='penalizaciones_p1',
            field=models.IntegerField(default=0, help_text='Penalizaciones'),
        ),
        migrations.AlterField(
            model_name='lucha',
            name='penalizaciones_p2',
            field=models.IntegerField(default=0, help_text='Penalizaciones'),
        ),
        migrations.AlterField(
            model_name='lucha',
            name='puntos_p1',
            field=models.IntegerField(default=0, help_text='Puntos totales'),
        ),
        migrations.AlterField(
            model_name='lucha',
            name='puntos_p2',
            field=models.IntegerField(default=0, help_text='Puntos totales'),
        ),
        migrations.AlterField(
            model_name='lucha',
            name='ventajas_p1',
            field=models.IntegerField(default=0, help_text='Ventajas'),
        ),
        migrations.AlterField(
            model_name='lucha',
            name='ventajas_p2',
            field=models.IntegerField(default=0, help_text='Ventajas'),
        ),
    ]
