# Generated by Django 5.2.4 on 2025-09-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_link_existing_participants_to_atleta'),
    ]

    operations = [
        # Eliminar modelos relacionados con torneos BJJ
        migrations.DeleteModel(
            name='AtletaPunto',
        ),
        migrations.DeleteModel(
            name='Lucha',
        ),
        migrations.DeleteModel(
            name='Llave',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Atleta',
        ),
        migrations.DeleteModel(
            name='Torneo',
        ),
    ]
