# Generated by Django 4.2.10 on 2025-08-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_torneo_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atleta',
            options={},
        ),
    ]
