# Generated by Django 5.2.6 on 2025-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_atleta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaitem',
            name='archivo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galeriaitem',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
